services:

  db:
    image: mysql:8.0
    container_name: kiosk-mysql
    environment:
      MYSQL_DATABASE: KIOSK_DB
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_conf/utf8.cnf:/etc/mysql/conf.d/utf8.cnf:ro # 로컬의 설정 -> 도커 설정
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped
    networks:
      - kiosk-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kiosk-app:latest
    container_name: kiosk-app
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8080:8080"

#    env_file:
#      - .env              # .env의 모든 키가 컨테이너로 주입됨

    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/KIOSK_DB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_HIKARI_INITIALIZATIONFAILTIMEOUT: "-1"



    restart: unless-stopped
    networks:
      - kiosk-network

volumes:
  mysql_data:
  lt_models:

networks:
  kiosk-network:
    driver: bridge





